## Libraries & Datasets

### Libraries

In [2]:
import pandas as pd
import numpy as np

### Reading Data

In [3]:
PlayerValuations = pd.read_csv(r'D:\Football Project\Datasets\player_valuations.csv')
PlayerPerformance = pd.read_csv(r'D:\Football Project\Datasets\game_events.csv')
Playerdetails = pd.read_csv(r'D:\Football Project\Datasets\players.csv')
Appearances = pd.read_csv(r'D:\Football Project\Datasets\appearances.csv')
Injuries = pd.read_excel(r'D:\Football Project\Datasets\Injuries.xlsx')

## Setting Up Datasets

### Grouping Market Value Per Year

In [4]:
import pandas as pd

df = PlayerValuations
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year

years_valuations = pd.DataFrame(df['player_id'].unique(), columns=['player_id'])

for year in range(2018, 2025):
    yearly_data = df[df['year'] == year].groupby('player_id', as_index=False)['market_value_in_eur'].max()
    yearly_data.rename(columns={'market_value_in_eur': f'value_{year}'}, inplace=True)
    years_valuations = years_valuations.merge(yearly_data, on='player_id', how='left')

years_valuations.fillna(0, inplace=True)

#### An Example: Mo Salah Market Value

In [5]:
years_valuations[years_valuations['player_id'] == 148455]

,player_id,value_2018,value_2019,value_2020,value_2021,value_2022,value_2023,value_2024
8153,148455,150000000.0,150000000.0,120000000.0,110000000.0,90000000.0,70000000.0,55000000.0

#### Dataset Info

In [6]:
## Percentage of Zeros per Each Year

years_valuations.eq(0).mean() * 100

player_id      0.000000
value_2018    42.715104
value_2019    39.426604
value_2020    38.857069
value_2021    34.201043
value_2022    34.136688
value_2023    34.194607
value_2024    69.122852
dtype: float64

In [7]:
## Statistics per each year

years_valuations.describe()

,player_id,value_2018,value_2019,value_2020,value_2021,value_2022,value_2023,value_2024
count,3.107800e+04,3.107800e+04,3.107800e+04,3.107800e+04,3.107800e+04,3.107800e+04,3.107800e+04,3.107800e+04
mean,3.292334e+05,1.325161e+06,1.533789e+06,1.440661e+06,1.487778e+06,1.486775e+06,1.599924e+06,1.468495e+06
std,2.685367e+05,6.052592e+06,6.573578e+06,5.906760e+06,5.861936e+06,5.829793e+06,6.379274e+06,6.754403e+06
min,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,9.934350e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.686130e+05,1.000000e+05,1.250000e+05,1.500000e+05,1.750000e+05,2.000000e+05,1.750000e+05,0.000000e+00
75%,5.007438e+05,5.000000e+05,6.000000e+05,6.000000e+05,6.000000e+05,6.000000e+05,6.000000e+05,2.500000e+05
max,1.310513e+06,2.000000e+08,2.000000e+08,1.800000e+08,1.600000e+08,1.800000e+08,1.800000e+08,2.000000e+08

#### Player Info

In [8]:
Playerdetails

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32596,1375876,NaN,Diego Henrique,Diego Henrique,2024,86209,diego-henrique,Brazil,"Andradina, SP",Brazil,...,left,170.0,2026-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/diego-henrique...,UKR1,FK Livyi Bereh,NaN,NaN
32597,1378362,Orseer,Achihi,Orseer Achihi,2024,1096,orseer-achihi,NaN,NaN,Nigeria,...,NaN,NaN,2029-06-30 00:00:00,Aneke/PMG,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/orseer-achihi/...,BE1,Royal Antwerp Football Club,NaN,NaN
32598,1380311,Prince Amoako,Junior,Prince Amoako Junior,2024,2778,prince-amoako-junior,NaN,NaN,Ghana,...,NaN,NaN,2029-12-31 00:00:00,CAA Stellar,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/prince-amoako-...,DK1,Fodbold Club Nordsjælland,NaN,NaN
32599,1380876,Gabriel Jesus,David,Gabriel Jesus David,2024,1096,gabriel-jesus-david,NaN,NaN,Nigeria,...,NaN,NaN,2025-06-30 00:00:00,Aneke/PMG,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/gabriel-jesus-...,BE1,Royal Antwerp Football Club,NaN,NaN
32600,1391239,Mohamed,Fofana,Mohamed Fofana,2024,601,mohamed-fofana,NaN,NaN,Cote d'Ivoire,...,right,NaN,2028-06-30 00:00:00,4FC,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/mohamed-fofana...,BE1,Koninklijke Voetbalclub Kortrijk,NaN,NaN

In [9]:
# Select the player_id and sub_position columns
player_info = Playerdetails[['player_id', 'sub_position','country_of_citizenship','name']]

### Setting Up Goals/Assits Dataset

#### Goals

In [10]:
# Assuming your 'date' column is in a datetime format
PlayerPerformance['date'] = pd.to_datetime(PlayerPerformance['date'])  # Ensure the 'date' column is in datetime format

# Create a new 'year' column by extracting the year from 'date'
PlayerPerformance['year'] = PlayerPerformance['date'].dt.year

# Display the DataFrame to confirm the new column
PlayerPerformance.head()

,game_event_id,date,game_id,minute,type,club_id,player_id,description,player_in_id,player_assist_id,year
0,2f41da30c471492e7d4a984951671677,2012-08-05,2211607,77,Cards,610,4425,"1. Yellow card , Mass confrontation",NaN,NaN,2012
1,a72f7186d132775f234d3e2f7bc0ed5b,2012-08-05,2211607,77,Cards,383,33210,"1. Yellow card , Mass confrontation",NaN,NaN,2012
2,b2d721eaed4692a5c59a92323689ef18,2012-08-05,2211607,3,Goals,383,36500,", Header, 1. Tournament Goal Assist: , Corner,...",NaN,56416.0,2012
3,aef768899cedac0c9a650980219075a2,2012-08-05,2211607,53,Goals,383,36500,", Right-footed shot, 2. Tournament Goal Assist...",NaN,146258.0,2012
4,5d6d9533023057b6619ecd145a038bbe,2012-08-05,2211607,74,Substitutions,383,36500,", Not reported",49499.0,NaN,2012

In [11]:
goals = PlayerPerformance[PlayerPerformance['type'] == 'Goals'][['year', 'player_id']]
goals

         year  player_id
2        2012      36500
3        2012      36500
5        2012      38497
7        2012      42710
9        2012      49499
...       ...        ...
1034988  2025     258923
1034996  2025     503749
1035007  2025     418560
1035009  2025     445939
1035013  2025     711337

[206320 rows x 2 columns]

In [12]:
# Initialize an empty DataFrame to store the results
playergoals = pd.DataFrame(goals['player_id'].unique(), columns=['player_id'])

# Loop through each year from 2014 to 2024
for year in range(2018, 2025):
    # Filter data for the specific year and count the number of rows per player_id (goals)
    yearly_data = goals[goals['year'] == year].groupby('player_id').size().reset_index(name='goals')
    
    # Rename the column for clarity
    yearly_data.rename(columns={'goals': f'goals_{year}'}, inplace=True)
    
    # Merge the yearly data into the goals_valuations DataFrame
    playergoals = playergoals.merge(yearly_data, on='player_id', how='left')

# Fill missing values with 0 (optional)
playergoals.fillna(0, inplace=True)

# Display the resulting DataFrame
playergoals.head()

,player_id,goals_2018,goals_2019,goals_2020,goals_2021,goals_2022,goals_2023,goals_2024
0,36500,0.0,0.0,1.0,0.0,3.0,0.0,0.0
1,38497,5.0,0.0,3.0,3.0,0.0,0.0,0.0
2,42710,0.0,1.0,4.0,1.0,2.0,4.0,5.0
3,49499,2.0,7.0,4.0,5.0,0.0,2.0,0.0
4,52920,4.0,1.0,0.0,4.0,1.0,0.0,0.0

##### An Example: Mo Salah Goals per Year

In [13]:
playergoals[playergoals['player_id'] == 148455]

,player_id,goals_2018,goals_2019,goals_2020,goals_2021,goals_2022,goals_2023,goals_2024
4960,148455,37.0,24.0,26.0,37.0,24.0,30.0,29.0

#### Assists

In [14]:
PlayerPerformance

,game_event_id,date,game_id,minute,type,club_id,player_id,description,player_in_id,player_assist_id,year
0,2f41da30c471492e7d4a984951671677,2012-08-05,2211607,77,Cards,610,4425,"1. Yellow card , Mass confrontation",NaN,NaN,2012
1,a72f7186d132775f234d3e2f7bc0ed5b,2012-08-05,2211607,77,Cards,383,33210,"1. Yellow card , Mass confrontation",NaN,NaN,2012
2,b2d721eaed4692a5c59a92323689ef18,2012-08-05,2211607,3,Goals,383,36500,", Header, 1. Tournament Goal Assist: , Corner,...",NaN,56416.0,2012
3,aef768899cedac0c9a650980219075a2,2012-08-05,2211607,53,Goals,383,36500,", Right-footed shot, 2. Tournament Goal Assist...",NaN,146258.0,2012
4,5d6d9533023057b6619ecd145a038bbe,2012-08-05,2211607,74,Substitutions,383,36500,", Not reported",49499.0,NaN,2012
...,...,...,...,...,...,...,...,...,...,...,...
1035038,fd6398da8baafd9d3fed4994482d34f1,2025-03-29,4572898,114,Cards,1237,700106,"1. Yellow card , Foul",NaN,NaN,2025
1035039,03ed12d2c5be9fc8a9d33c7d32a9fc02,2025-03-29,4572898,-1,Shootout,1237,700106,", Scored",NaN,NaN,2025
1035040,ae97664fa1743abd0cbc8b8b6e3df9af,2025-03-29,4572898,61,Substitutions,703,808509,", Tactical",392768.0,NaN,2025
1035041,e6b9a6e8764febebf29804b7d486efbc,2025-03-29,4572898,-1,Shootout,1237,867688,", Saved",NaN,NaN,2025
1035042,3c606b4b6ce2376258ef46f9deb0327a,2025-03-29,4572898,-1,Shootout,1237,996897,", Saved",NaN,NaN,2025

In [15]:
Assists = PlayerPerformance[PlayerPerformance['type'] == 'Goals'][['year','player_assist_id']]
Assists

         year  player_assist_id
2        2012           56416.0
3        2012          146258.0
5        2012           33210.0
7        2012            4425.0
9        2012          167850.0
...       ...               ...
1034988  2025               NaN
1034996  2025          126664.0
1035007  2025          743413.0
1035009  2025          743413.0
1035013  2025          330659.0

[206320 rows x 2 columns]

In [16]:
# Initialize an empty DataFrame to store the results
playerassists = pd.DataFrame(Assists['player_assist_id'].unique(), columns=['player_assist_id'])

# Loop through each year from 2014 to 2024
for year in range(2018, 2025):
    # Filter data for the specific year and count the number of rows per player_id (assists)
    yearly_data = Assists[Assists['year'] == year].groupby('player_assist_id').size().reset_index(name='assists')
    
    # Rename the column to reflect the year (e.g., 'year_2014_assists')
    yearly_data.rename(columns={'assists': f'assists_{year}'}, inplace=True)
    
    # Merge the yearly data into the playerassists DataFrame
    playerassists = playerassists.merge(yearly_data, on='player_assist_id', how='left')

# Fill missing values with 0 (optional)
playerassists.fillna(0, inplace=True)

# Display the resulting DataFrame
playerassists.head()

,player_assist_id,assists_2018,assists_2019,assists_2020,assists_2021,assists_2022,assists_2023,assists_2024
0,56416.0,5.0,11.0,14.0,2.0,3.0,6.0,27.0
1,146258.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0
2,33210.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4425.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,167850.0,20.0,6.0,5.0,12.0,0.0,0.0,2.0

In [17]:
playerassists.rename(columns={'player_assist_id': 'player_id'}, inplace=True)

##### An Example: Mo Salah Assists per Year

In [18]:
playerassists[playerassists['player_id'] == 148455]

,player_id,assists_2018,assists_2019,assists_2020,assists_2021,assists_2022,assists_2023,assists_2024
3683,148455.0,18.0,11.0,10.0,11.0,12.0,18.0,23.0

#### Appearances

In [19]:
Appearances=pd.read_csv(r'D:\Football Project\Datasets\appearances.csv')

In [20]:
# Convert 'date' column to datetime
Appearances['date'] = pd.to_datetime(Appearances['date'], errors='coerce')

# Now extract the year and group by it
Appearances['year'] = Appearances['date'].dt.year

# Group by year and count the rows
appearances_per_year = Appearances.groupby('year').size()

# Display the result
appearances_per_year

year
2012     71688
2013    129862
2014    125776
2015    132338
2016    131075
2017    135103
2018    126996
2019    128672
2020    114160
2021    147383
2022    129335
2023    150698
2024    137987
2025     45733
dtype: int64

In [21]:
# First, ensure the 'date' column is in datetime format and extract the year
Appearances['date'] = pd.to_datetime(Appearances['date'], errors='coerce')
Appearances['year'] = Appearances['date'].dt.year

# Filter for years between 2019 and 2024
filtered_appearances = Appearances[Appearances['year'].between(2019, 2024)]

# Group by player_id and year, sum minutes_played, and unstack
sum_minutes = filtered_appearances.groupby(['player_id', 'year'])['minutes_played'].sum().unstack(fill_value=0)

# Check for continuous zeros over 3 or more years
continuous_zero_filter = sum_minutes.apply(lambda row: any(row[i:i+2].eq(0).all() for i in range(len(row) - 1)), axis=1)

# Remove rows where there are 3 consecutive years with zero minutes
sum_minutes_cleaned = sum_minutes[~continuous_zero_filter]
sum_minutes_cleaned = sum_minutes_cleaned.rename(columns={col: f"minutes_{col}" for col in sum_minutes_cleaned.columns})

sum_minutes_cleaned

year,minutes_2019,minutes_2020,minutes_2021,minutes_2022,minutes_2023,minutes_2024
player_id,,,,,,
3333,2389,1115,1652,1174,1390,354
3455,0,2301,2007,303,144,0
4391,0,720,1016,630,0,5
4742,1088,618,741,728,1208,0
5336,1804,1232,2166,2067,1628,987
...,...,...,...,...,...,...
818285,0,120,90,90,90,120
821535,0,163,1084,185,486,1065
830079,0,74,180,488,574,0
841121,0,133,61,0,71,201
847759,0,1,768,668,276,88

#### Injuries

In [22]:
# Convert the 'from' column to datetime format
Injuries['from'] = pd.to_datetime(Injuries['from'], errors='coerce')

# Extract the year from the 'from' date
Injuries['year'] = Injuries['from'].dt.year

# Filter for years 2019 to 2022
Injuries_filtered = Injuries[Injuries['year'].between(2019, 2024)]

# Group by player_id and year, count injuries
injuries_per_year = Injuries_filtered.groupby(['player_id', 'year']).size().unstack(fill_value=0)

# Rename columns to 'injuries_<year>'
injuries_per_year.columns = [f'injuries_{col}' for col in injuries_per_year.columns]

# Display the result
injuries_per_year

,injuries_2019.0,injuries_2020.0,injuries_2021.0,injuries_2022.0,injuries_2023.0,injuries_2024.0
player_id,,,,,,
532,2,2,0,0,0,0
1094,1,0,0,0,0,0
1126,12,0,0,0,0,0
1257,0,1,0,0,0,0
1586,1,0,0,0,0,0
...,...,...,...,...,...,...
1046796,0,0,0,0,2,0
1050249,0,0,0,0,1,0
1052404,0,0,0,1,0,0
1053240,0,0,0,0,1,0
1103981,0,0,0,0,1,0

#### Player Club

In [23]:
Playerdetails

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32596,1375876,NaN,Diego Henrique,Diego Henrique,2024,86209,diego-henrique,Brazil,"Andradina, SP",Brazil,...,left,170.0,2026-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/diego-henrique...,UKR1,FK Livyi Bereh,NaN,NaN
32597,1378362,Orseer,Achihi,Orseer Achihi,2024,1096,orseer-achihi,NaN,NaN,Nigeria,...,NaN,NaN,2029-06-30 00:00:00,Aneke/PMG,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/orseer-achihi/...,BE1,Royal Antwerp Football Club,NaN,NaN
32598,1380311,Prince Amoako,Junior,Prince Amoako Junior,2024,2778,prince-amoako-junior,NaN,NaN,Ghana,...,NaN,NaN,2029-12-31 00:00:00,CAA Stellar,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/prince-amoako-...,DK1,Fodbold Club Nordsjælland,NaN,NaN
32599,1380876,Gabriel Jesus,David,Gabriel Jesus David,2024,1096,gabriel-jesus-david,NaN,NaN,Nigeria,...,NaN,NaN,2025-06-30 00:00:00,Aneke/PMG,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/gabriel-jesus-...,BE1,Royal Antwerp Football Club,NaN,NaN
32600,1391239,Mohamed,Fofana,Mohamed Fofana,2024,601,mohamed-fofana,NaN,NaN,Cote d'Ivoire,...,right,NaN,2028-06-30 00:00:00,4FC,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/mohamed-fofana...,BE1,Koninklijke Voetbalclub Kortrijk,NaN,NaN

## Final Datasets

In [24]:
years_valuations

,player_id,value_2018,value_2019,value_2020,value_2021,value_2022,value_2023,value_2024
0,405973,75000.0,50000.0,50000.0,50000.0,0.0,0.0,0.0
1,342216,2000000.0,1500000.0,900000.0,900000.0,250000.0,0.0,0.0
2,3132,100000.0,0.0,0.0,0.0,0.0,0.0,0.0
3,6893,400000.0,300000.0,250000.0,300000.0,300000.0,100000.0,0.0
4,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
31073,1061378,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31074,1081566,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31075,1178475,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31076,1234104,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31077,897423,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
playergoals

,player_id,goals_2018,goals_2019,goals_2020,goals_2021,goals_2022,goals_2023,goals_2024
0,36500,0.0,0.0,1.0,0.0,3.0,0.0,0.0
1,38497,5.0,0.0,3.0,3.0,0.0,0.0,0.0
2,42710,0.0,1.0,4.0,1.0,2.0,4.0,5.0
3,49499,2.0,7.0,4.0,5.0,0.0,2.0,0.0
4,52920,4.0,1.0,0.0,4.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
29719,962110,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29720,346478,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29721,526694,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29722,528515,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29723,658060,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
playerassists

,player_id,assists_2018,assists_2019,assists_2020,assists_2021,assists_2022,assists_2023,assists_2024
0,56416.0,5.0,11.0,14.0,2.0,3.0,6.0,27.0
1,146258.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0
2,33210.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4425.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,167850.0,20.0,6.0,5.0,12.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...
24592,644607.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24593,591916.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24594,605265.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24595,363740.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24596,743413.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
sum_minutes_cleaned

year,minutes_2019,minutes_2020,minutes_2021,minutes_2022,minutes_2023,minutes_2024
player_id,,,,,,
3333,2389,1115,1652,1174,1390,354
3455,0,2301,2007,303,144,0
4391,0,720,1016,630,0,5
4742,1088,618,741,728,1208,0
5336,1804,1232,2166,2067,1628,987
...,...,...,...,...,...,...
818285,0,120,90,90,90,120
821535,0,163,1084,185,486,1065
830079,0,74,180,488,574,0
841121,0,133,61,0,71,201
847759,0,1,768,668,276,88

## Merging Datasets

In [28]:
#removing all zeros

years_valuations = years_valuations[(years_valuations != 0).all(axis=1)]
years_valuations

,player_id,value_2018,value_2019,value_2020,value_2021,value_2022,value_2023,value_2024
187,3333,15000000.0,15000000.0,8000000.0,3000000.0,2000000.0,1500000.0,1000000.0
345,4391,600000.0,300000.0,250000.0,200000.0,100000.0,75000.0,50000.0
785,9500,2000000.0,1500000.0,500000.0,250000.0,250000.0,200000.0,50000.0
888,12029,500000.0,500000.0,250000.0,250000.0,100000.0,100000.0,100000.0
906,12359,250000.0,500000.0,250000.0,200000.0,200000.0,100000.0,75000.0
...,...,...,...,...,...,...,...,...
22687,552057,200000.0,7500000.0,12000000.0,19000000.0,20000000.0,18000000.0,18000000.0
22688,564785,400000.0,1000000.0,2000000.0,6000000.0,8500000.0,7500000.0,8000000.0
22690,585339,250000.0,500000.0,750000.0,1200000.0,1500000.0,700000.0,1000000.0
22695,551505,1500000.0,2000000.0,2000000.0,1500000.0,1800000.0,6000000.0,8000000.0
22696,631927,50000.0,150000.0,250000.0,850000.0,1700000.0,2800000.0,4000000.0

In [29]:
import pandas as pd

# Ensure the column is in datetime format
Playerdetails['contract_expiration_date'] = pd.to_datetime(Playerdetails['contract_expiration_date'])

# Create a feature: Days until contract expiration
Playerdetails['days_until_expiration'] = (Playerdetails['contract_expiration_date'] - pd.Timestamp.today()).dt.days

# Replace NaN values with 0
Playerdetails['days_until_expiration'] = Playerdetails['days_until_expiration'].fillna(0)

# Keep only the necessary columns
selected_data = Playerdetails[['player_id', 'days_until_expiration']]

# Display the result
print(selected_data.head())

   player_id  days_until_expiration
0         10                    0.0
1         26                    0.0
2         65                    0.0
3         77                    0.0
4         80                    0.0

In [30]:
import pandas as pd

# Assuming you have three DataFrames: years_valuations, playergoals, and playerassists
# Merging all three on 'player_id'

merged_df = pd.merge(years_valuations, playergoals, on='player_id', how='left')
merged_df = pd.merge(merged_df, playerassists, on='player_id', how='left')
merged_df = pd.merge(merged_df, selected_data, on='player_id', how='left')
merged_df = pd.merge(merged_df, sum_minutes_cleaned, on='player_id', how='left')
merged_df = pd.merge(merged_df, player_info, on='player_id', how='left')
merged_df = pd.merge(merged_df, injuries_per_year, on='player_id', how='left')

In [31]:
merged_df.fillna(0, inplace=True)
merged_df

,player_id,value_2018,value_2019,value_2020,value_2021,value_2022,value_2023,value_2024,goals_2018,goals_2019,...,minutes_2024,sub_position,country_of_citizenship,name,injuries_2019.0,injuries_2020.0,injuries_2021.0,injuries_2022.0,injuries_2023.0,injuries_2024.0
0,3333,15000000.0,15000000.0,8000000.0,3000000.0,2000000.0,1500000.0,1000000.0,7.0,4.0,...,354.0,Central Midfield,England,James Milner,1.0,6.0,3.0,2.0,1.0,0.0
1,4391,600000.0,300000.0,250000.0,200000.0,100000.0,75000.0,50000.0,0.0,0.0,...,5.0,Goalkeeper,Netherlands,Boy Waterman,0.0,0.0,0.0,1.0,0.0,0.0
2,9500,2000000.0,1500000.0,500000.0,250000.0,250000.0,200000.0,50000.0,0.0,0.0,...,0.0,Goalkeeper,Scotland,David Marshall,0.0,0.0,1.0,0.0,1.0,0.0
3,12029,500000.0,500000.0,250000.0,250000.0,100000.0,100000.0,100000.0,1.0,0.0,...,0.0,Goalkeeper,France,Ludovic Butelle,0.0,0.0,0.0,0.0,0.0,0.0
4,12359,250000.0,500000.0,250000.0,200000.0,200000.0,100000.0,75000.0,0.0,0.0,...,0.0,Goalkeeper,Finland,Niki Mäenpää,0.0,0.0,3.0,2.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4473,552057,200000.0,7500000.0,12000000.0,19000000.0,20000000.0,18000000.0,18000000.0,0.0,1.0,...,0.0,Second Striker,Czech Republic,Adam Hlozek,1.0,3.0,2.0,0.0,1.0,0.0
4474,564785,400000.0,1000000.0,2000000.0,6000000.0,8500000.0,7500000.0,8000000.0,0.0,0.0,...,1467.0,Attacking Midfield,Norway,Kristian Thorstvedt,0.0,2.0,1.0,0.0,1.0,0.0
4475,585339,250000.0,500000.0,750000.0,1200000.0,1500000.0,700000.0,1000000.0,0.0,0.0,...,359.0,Centre-Forward,Senegal,Pape Habib Guèye,0.0,0.0,1.0,0.0,0.0,0.0
4476,551505,1500000.0,2000000.0,2000000.0,1500000.0,1800000.0,6000000.0,8000000.0,0.0,0.0,...,1334.0,Right Winger,Jordan,Mousa Tamari,0.0,0.0,0.0,0.0,1.0,0.0
4477,631927,50000.0,150000.0,250000.0,850000.0,1700000.0,2800000.0,4000000.0,0.0,0.0,...,0.0,Right-Back,Saudi Arabia,Saud Abdulhamid,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
# Display all column names of the merged DataFrame
print(merged_df.columns)

Index(['player_id', 'value_2018', 'value_2019', 'value_2020', 'value_2021',
       'value_2022', 'value_2023', 'value_2024', 'goals_2018', 'goals_2019',
       'goals_2020', 'goals_2021', 'goals_2022', 'goals_2023', 'goals_2024',
       'assists_2018', 'assists_2019', 'assists_2020', 'assists_2021',
       'assists_2022', 'assists_2023', 'assists_2024', 'days_until_expiration',
       'minutes_2019', 'minutes_2020', 'minutes_2021', 'minutes_2022',
       'minutes_2023', 'minutes_2024', 'sub_position',
       'country_of_citizenship', 'name', 'injuries_2019.0', 'injuries_2020.0',
       'injuries_2021.0', 'injuries_2022.0', 'injuries_2023.0',
       'injuries_2024.0'],
      dtype='object')

In [33]:
from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Encode the 'country_of_citizenship' column
merged_df['country_of_citizenship_encoded'] = label_encoder.fit_transform(merged_df['country_of_citizenship'])

# Encode the 'sub_position' column
merged_df['sub_position_encoded'] = label_encoder.fit_transform(merged_df['sub_position'])

In [35]:
merged_df.to_csv('merged_df.csv', index=False)